// ============================================================
//  lib/firebase_options.dart
//  PLACEHOLDER — This file must be generated by running:
//
//    dart pub global activate flutterfire_cli
//    flutterfire configure
//
//  See FIREBASE_SETUP.md for full instructions.
//  Do NOT manually edit this file after generation.
//
//  This placeholder prevents compilation errors while Firebase
//  is not yet configured. Replace this entire file with the
//  generated output from flutterfire configure.
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Replace this with the real generated file from flutterfire configure.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'SecureLink does not support Web. Android only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'SecureLink does not support iOS in this build.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️  REPLACE THE VALUES BELOW WITH YOUR ACTUAL FIREBASE CONFIG ⚠️
  // Run: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtC-_OJBWWuViHm47zHaY86uYaNRI9Ngs',
    appId: '1:235672247006:android:82f0466be9b6736248004f',
    messagingSenderId: '235672247006',
    projectId: 'linkfyp2',
    storageBucket: 'linkfyp2.firebasestorage.app',
  );

  // This will auto-fill all the fields below.
}